version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dat789qu
      - MYSQL_DATABASE=quanlybanhang
      - MYSQL_ROOT_PASSWORD=dat789qu
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3336:3306

  web:
    image: shopping-app
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql-data: